import Link from 'next/link';
import { SEO } from '@/components/SEO';
import { DesignPreview } from '@/components/DesignPreview';
import { designTiers, designs } from '@/lib/design-catalogue';
export default function Templates() {
  return <><SEO title="Website design directions & templates — APEXWEB" description="Explore 30 website design directions across APEXWEB Starter, Local Business and Growth packages. Choose a style to shape your custom website." />
    <div className="template-shell"><section className="template-hero"><p className="eyebrow">THE APEXWEB DESIGN COLLECTION / 30 DIRECTIONS</p><h1>Find your<br /><em>starting point.</em></h1><div className="template-intro"><p>A website should feel like your business. Explore three levels of design, then find the direction that feels right for you.</p><p>Every direction is adapted to your brand, services and customers. The visuals here show art direction; complete interactive demos will be added as they are built.</p></div></section>
    <section className="tier-collection" aria-label="Choose your website tier">{designTiers.map(tier => <Link key={tier.slug} href={`/templates/${tier.slug}`} className="tier-collection-card"><div className="tier-top"><span>0{tier.number} / TEN DIRECTIONS</span><span>FROM ${tier.price} AUD</span></div><DesignPreview design={designs.find(d=>d.tier===tier.slug)!} /><div className="tier-bottom"><div><h2>{tier.name}</h2><p>{tier.description}</p></div><span className="tier-arrow" aria-hidden="true">↗</span></div><p className="tier-scope">{tier.scope}</p></Link>)}</section>
    <section className="template-process"><p className="eyebrow">FROM A DIRECTION TO YOUR WEBSITE</p><h2>A starting point.<br />A result that is yours.</h2><ol><li><span>01</span><h3>Choose your direction</h3><p>Pick a package and explore its ten themes. Save the direction number or send us the page link.</p></li><li><span>02</span><h3>Make it your business</h3><p>We plan your real content, images, pages and tools, then confirm the scope and final quote.</p></li><li><span>03</span><h3>Build, check and launch</h3><p>Your website is built and tested across devices, with search essentials, security checks and a launch handover.</p></li></ol><Link href="/quote" className="button">Talk about your website ↗</Link></section></div></>;
}
