import Link from 'next/link';
import type { GetStaticPaths, GetStaticProps } from 'next';
import { SEO } from '@/components/SEO';
import { DesignPreview } from '@/components/DesignPreview';
import { designs, designTiers } from '@/lib/design-catalogue';
import type { Design, DesignTier } from '@/lib/template-types';
export default function Direction({ design, tier }: {design:Design;tier:DesignTier}) {
  const collection=designs.filter(d=>d.tier===tier.slug), index=collection.findIndex(d=>d.id===design.id); const previous=collection[(index+9)%10],next=collection[(index+1)%10];
  return <><SEO title={`${design.title} — ${tier.name} website direction | APEXWEB`} description={design.summary} /><div className="template-shell"><nav className="template-breadcrumb" aria-label="Breadcrumb"><Link href="/templates">Collection</Link><span aria-hidden="true">/</span><Link href={`/templates/${tier.slug}`}>{tier.name}</Link><span aria-hidden="true">/</span><span>{design.id}</span></nav><section className="direction-header"><div><p className="eyebrow">DIRECTION {design.id} / {tier.name.toUpperCase()}</p><h1>{design.title}</h1><p>{design.summary}</p></div><div className="direction-actions"><Link className="button" href={`/quote?package=${tier.slug}&source=template-${design.id}`}>Choose this direction ↗</Link><Link className="button button-outline" href={`/templates/${tier.slug}`}>See all ten directions</Link></div></section><DesignPreview design={design} large /><section className="direction-details"><div><p className="eyebrow">THE CREATIVE IDEA</p><h2>{design.signature}</h2><h3>Well suited to</h3><p>{design.audience}</p><h3>Typography</h3><p>{design.typography}</p><h3>Palette direction</h3><div className="palette-swatches">{design.palette.map(c=><div key={c}><i style={{background:c}} aria-hidden="true"/><code>{c}</code></div>)}</div></div><aside className="direction-demo"><p className="eyebrow">THE FULL EXPERIENCE</p><h2>{design.demoUrl?'Explore the live demo.':'Your next preview is taking shape.'}</h2><p>{design.demoUrl?'Open the complete demonstration to explore its pages and interactions. Demonstration content is adapted to your own business during your project.':'The build prompt and design direction are prepared. The complete demonstration website has not been built yet. This page will link to it when it is ready.'}</p>{design.demoUrl?<a className="button" href={design.demoUrl} target="_blank" rel="noopener noreferrer">Open live demo ↗</a>:<span className="demo-status">DEMO COMING SOON</span>}<p className="direction-id">Selection reference: <strong>{design.id}</strong></p><p>{tier.scope}</p></aside></section><section className="direction-chapters"><p className="eyebrow">{tier.slug==='growth'?'THE STORY JOURNEY':'THE DESIGN RHYTHM'}</p><h2>A coherent experience,<br />from first impression to enquiry.</h2><ol>{design.chapters.map((c,i)=><li key={c}><span>{String(i+1).padStart(2,'0')}</span><h3>{c}</h3></li>)}</ol><p>Real services, genuine evidence, responsive layouts and accessible alternatives shape the final build. Custom animation in Starter requires a separately agreed add-on.</p></section><nav className="direction-pagination" aria-label="Explore more directions"><Link href={`/templates/${tier.slug}/${previous.slug}`}><small>← PREVIOUS</small><span>{previous.title}</span></Link><Link href={`/templates/${tier.slug}/${next.slug}`}><small>NEXT →</small><span>{next.title}</span></Link></nav></div></>;
}
export const getStaticPaths: GetStaticPaths = async()=>({paths:designs.map(d=>({params:{tier:d.tier,design:d.slug}})),fallback:false});
export const getStaticProps: GetStaticProps=async({params})=>{const design=designs.find(d=>d.tier===params?.tier&&d.slug===params?.design);const tier=designTiers.find(t=>t.slug===params?.tier);return design&&tier?{props:{design,tier}}:{notFound:true};};
